
trigger:
- master

strategy:
  matrix:

    msvc-x86-debug:
      buildPlatform: 'x86'
      buildConfiguration: 'MSVC_Debug'
    msvc-x86-release:
      buildPlatform: 'x86'
      buildConfiguration: 'MSVC_Release'
    msvc-x86-retail:
      buildPlatform: 'x86'
      buildConfiguration: 'MSVC_Retail'

    msvc-x64-debug:
      buildPlatform: 'x64'
      buildConfiguration: 'MSVC_Debug'
    msvc-x64-release:
      buildPlatform: 'x64'
      buildConfiguration: 'MSVC_Release'
    msvc-x64-retail:
      buildPlatform: 'x64'
      buildConfiguration: 'MSVC_Retail'

    msvc-arm-debug:
      buildPlatform: 'ARM'
      buildConfiguration: 'MSVC_Debug'
    msvc-arm-release:
      buildPlatform: 'ARM'
      buildConfiguration: 'MSVC_Release'
    msvc-arm-retail:
      buildPlatform: 'ARM'
      buildConfiguration: 'MSVC_Retail'

    msvc-arm64-debug:
      buildPlatform: 'ARM64'
      buildConfiguration: 'MSVC_Debug'
    msvc-arm64-release:
      buildPlatform: 'ARM64'
      buildConfiguration: 'MSVC_Release'
    msvc-arm64-retail:
      buildPlatform: 'ARM64'
      buildConfiguration: 'MSVC_Retail'

    llvm-x86-debug:
      buildPlatform: 'x86'
      buildConfiguration: 'LLVM_Debug'
    llvm-x86-release:
      buildPlatform: 'x86'
      buildConfiguration: 'LLVM_Release'
    llvm-x86-retail:
      buildPlatform: 'x86'
      buildConfiguration: 'LLVM_Retail'

    llvm-x64-debug:
      buildPlatform: 'x64'
      buildConfiguration: 'LLVM_Debug'
    llvm-x64-release:
      buildPlatform: 'x64'
      buildConfiguration: 'LLVM_Release'
    llvm-x64-retail:
      buildPlatform: 'x64'
      buildConfiguration: 'LLVM_Retail'

#    llvm-arm-debug:
#      buildPlatform: 'ARM'
#      buildConfiguration: 'LLVM_Debug'
#    llvm-arm-release:
#      buildPlatform: 'ARM'
#      buildConfiguration: 'LLVM_Release'
#    llvm-arm-retail:
#      buildPlatform: 'ARM'
#      buildConfiguration: 'LLVM_Retail'

#    llvm-arm64-debug:
#      buildPlatform: 'ARM64'
#      buildConfiguration: 'LLVM_Debug'
#    llvm-arm64-release:
#      buildPlatform: 'ARM64'
#      buildConfiguration: 'LLVM_Release'
#    llvm-arm64-retail:
#      buildPlatform: 'ARM64'
#      buildConfiguration: 'LLVM_Retail'

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'retrofit.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:RFBuildMachine=Azure'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_artifacts'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'

- task: CmdLine@2
  condition: eq(variables['buildPlatform'], 'x64')
  timeoutInMinutes: 1
  inputs:
    script: 'core_test.exe --nopause'
    workingDirectory: '_artifacts/$(buildPlatform)/$(buildConfiguration)/Out/'
    failOnStderr: true

- task: CmdLine@2
  condition: eq(variables['buildPlatform'], 'x64')
  timeoutInMinutes: 1
  inputs:
    script: 'foundation_test.exe --nopause'
    workingDirectory: '_artifacts/$(buildPlatform)/$(buildConfiguration)/Out/'
    failOnStderr: true
