
trigger:
- master

strategy:
  matrix:

    x86-debug:
      buildPlatform: 'x86'
      buildConfiguration: 'MSVC_Debug'
    x86-release:
      buildPlatform: 'x86'
      buildConfiguration: 'MSVC_Release'
    x86-retail:
      buildPlatform: 'x86'
      buildConfiguration: 'MSVC_Retail'

    x64-debug:
      buildPlatform: 'x64'
      buildConfiguration: 'MSVC_Debug'
    x64-release:
      buildPlatform: 'x64'
      buildConfiguration: 'MSVC_Release'
    x64-retail:
      buildPlatform: 'x64'
      buildConfiguration: 'MSVC_Retail'

    arm-debug:
      buildPlatform: 'ARM'
      buildConfiguration: 'MSVC_Debug'
    arm-release:
      buildPlatform: 'ARM'
      buildConfiguration: 'MSVC_Release'
    arm-retail:
      buildPlatform: 'ARM'
      buildConfiguration: 'MSVC_Retail'

    arm64-debug:
      buildPlatform: 'ARM64'
      buildConfiguration: 'MSVC_Debug'
    arm64-release:
      buildPlatform: 'ARM64'
      buildConfiguration: 'MSVC_Release'
    arm64-retail:
      buildPlatform: 'ARM64'
      buildConfiguration: 'MSVC_Retail'

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'retrofit.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_artifacts'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'
