# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

strategy:
  matrix:

    x86-debug:
      buildPlatform: 'x86'
      buildConfiguration: 'Debug'
    x86-release:
      buildPlatform: 'x86'
      buildConfiguration: 'Release'
    x86-retail:
      buildPlatform: 'x86'
      buildConfiguration: 'Retail'

    x64-debug:
      buildPlatform: 'x64'
      buildConfiguration: 'Debug'
    x64-release:
      buildPlatform: 'x64'
      buildConfiguration: 'Release'
    x64-retail:
      buildPlatform: 'x64'
      buildConfiguration: 'Retail'

    arm-debug:
      buildPlatform: 'ARM'
      buildConfiguration: 'Debug'
    arm-release:
      buildPlatform: 'ARM'
      buildConfiguration: 'Release'
    arm-retail:
      buildPlatform: 'ARM'
      buildConfiguration: 'Retail'

    arm64-debug:
      buildPlatform: 'ARM64'
      buildConfiguration: 'Debug'
    arm64-release:
      buildPlatform: 'ARM64'
      buildConfiguration: 'Release'
    arm64-retail:
      buildPlatform: 'ARM64'
      buildConfiguration: 'Retail'

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'retrofit.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '_artifacts'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'
