@cls
_artifacts\x64\Debug\Out\core_test.exe
_artifacts\x64\Release\Out\core_test.exe
_artifacts\x64\Retail\Out\core_test.exe
_artifacts\x86\Debug\Out\core_test.exe
_artifacts\x86\Release\Out\core_test.exe
_artifacts\x86\Retail\Out\core_test.exe
_artifacts\LLVM_x64\Debug\Out\core_test.exe
_artifacts\LLVM_x64\Release\Out\core_test.exe
_artifacts\LLVM_x64\Retail\Out\core_test.exe

_artifacts\x64\Debug\Out\foundation_test.exe
_artifacts\x64\Release\Out\foundation_test.exe
_artifacts\x64\Retail\Out\foundation_test.exe
_artifacts\x86\Debug\Out\foundation_test.exe
_artifacts\x86\Release\Out\foundation_test.exe
_artifacts\x86\Retail\Out\foundation_test.exe
_artifacts\LLVM_x64\Debug\Out\foundation_test.exe
_artifacts\LLVM_x64\Release\Out\foundation_test.exe
_artifacts\LLVM_x64\Retail\Out\foundation_test.exe
